name = "Heuli-Modback Ullrichmon"
author = "VollmondHeuler"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4d6d99ba60d550340bfe922f5fb7483dfc328b176fd762cabdaf1c9052f3ad5"

[versions]
minecraft = "1.21.1"
quilt = "0.29.1-beta.1"
