# Enable multiple mega's at one time
# Allowed values: true, false - Default: false
multipleMegas = false

# Enable mega evolution only for battles
# Allowed values: true, false - Default: false
battleModeOnly = false

# Allows you to have outside mega's but they devolve on battle and then you can have battle mode style theme
# Allowed values: true, false - Default: true
battleMode = true

# Allows you to have multiple primals at a time
# Allowed values: true, false - Default: true
multiplePrimals = true

# Allows you to have both the mega btn and allows u to carry your mega's into the battle, battleMode should be false for this
# Allowed values: true, false - Default: false
scuffedMode = false

